=== touchbit/openapi-example-project/_common/resources/schemas/version_probe.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "common-component/schemas/dto/version.json",
  "title": "version",
  "description": "Service version DTO",
  "type": "object",
  "required": ["name", "version", "revision"],
  "properties": {
    "name": {
      "type": "string",
      "description": "Service name"
    },
    "version": {
      "type": "string",
      "description": "Service version"
    },
    "revision": {
      "type": "string",
      "description": "Service revision"
    },
    "contracts": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "description": "Dependent service API contracts (optional)",
      "items": {
        "type": "object",
        "required": ["version", "name"],
        "properties": {
          "name": {
            "type": "string",
            "description": "Service contract name"
          },
          "version": {
            "type": "string",
            "description": "Service contract version"
          },
          "revision": {
            "type": "string",
            "description": "Service contract revision (optional)"
          }
        }
      }
    }
  }
}

=== touchbit/openapi-example-project/_common/resources/examples/version.json
{
  "name": "petstore-service",
  "version": "v1.33.1",
  "revision": "556cafd4",
  "contracts": [
    {
      "name": "identity-service",
      "version": "v1.14.0",
      "revision": "683ee43d"
    },
    {
      "name": "kyc-service",
      "version": "v1.2.14",
      "revision": "daff43d4"
    }
  ]
}
